insert into snapshot values (
    null,
    strftime('%Y-%m-%d %H:%M:%f', 'now'),
    :hostname,
    :uptime,
    :uptime_idle,
    :one_minute_load,
    :five_minute_load,
    :fifteen_minute_load,
    :running_threads,
    :total_threads,
    :last_pid,
    :free_pages,
    :pages_paged_in,
    :pages_paged_out,
    :pages_swapped_in,
    :pages_swapped_out,
    :pages_allocated_normal,
    :pages_freed,
    :pages_activated,
    :pages_deactivated,
    :pages_outrun,
    :alloc_stalled
);